### ISSUE TITLE
cryptominisat failed to build on high-sierra

### ISSUE THREAD

**Issue by chenrui333** [msoos/cryptominisat#617] opened 2020-05-12 04:47 UTC
relates to https://github.com/Homebrew/homebrew-core/pull/53731

Build failure log (Full log in the GHA run, https://github.com/Homebrew/homebrew-core/runs/648423544)
```
building 'pycryptosat' extension
creating build
creating build/temp.macosx-10.13-x86_64-3.8
creating build/temp.macosx-10.13-x86_64-3.8/tmp
creating build/temp.macosx-10.13-x86_64-3.8/tmp/cryptominisat-20200426-63099-1g3bdr4
creating build/temp.macosx-10.13-x86_64-3.8/tmp/cryptominisat-20200426-63099-1g3bdr4/cryptominisat-5.7.0
creating build/temp.macosx-10.13-x86_64-3.8/tmp/cryptominisat-20200426-63099-1g3bdr4/cryptominisat-5.7.0/build
creating build/temp.macosx-10.13-x86_64-3.8/tmp/cryptominisat-20200426-63099-1g3bdr4/cryptominisat-5.7.0/build/pycryptosat
creating build/temp.macosx-10.13-x86_64-3.8/tmp/cryptominisat-20200426-63099-1g3bdr4/cryptominisat-5.7.0/build/pycryptosat/src
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -g -W -Wall -Wno-deprecated -std=c++11 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -DLIBRARY_VERSION="5.7.0" -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c /tmp/cryptominisat-20200426-63099-1g3bdr4/cryptominisat-5.7.0/build/pycryptosat/src/pycryptosat.cpp -o build/temp.macosx-10.13-x86_64-3.8/tmp/cryptominisat-20200426-63099-1g3bdr4/cryptominisat-5.7.0/build/pycryptosat/src/pycryptosat.o -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/tmp/cryptominisat-20200426-63099-1g3bdr4/cryptominisat-5.7.0 -I/tmp/cryptominisat-20200426-63099-1g3bdr4/cryptominisat-5.7.0/build/cmsat5-src
In file included from /tmp/cryptominisat-20200426-63099-1g3bdr4/cryptominisat-5.7.0/build/pycryptosat/src/pycryptosat.cpp:27:
In file included from /usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/include/python3.8/Python.h:25:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
#include_next <stdio.h>
              ^~~~~~~~~
1 error generated.
```

**Comment by msoos** [comment] 2020-05-12 21:41
Hi! Thanks for the bug report! Do you know if this is an error of CryptoMiniSat? We don't seem to include stdio.h -- the error also seems to be from the Python.h that we never install, if I understand correctly? So I'm not sure this is actually an issue that's related to us, rather than the system you are compiling it on. The build also seems to be passing on MacOSX here:

https://travis-ci.org/github/msoos/cryptominisat

Can you please check what may be off?

Thanks again for the report,

Mate

**Comment by chenrui333** [comment] 2020-05-17 16:23
hI Mike, it looks like the osx 10.13 is missed from the cross-compilation build. Let me submit a PR to see if the build passes thru.

**Comment by msoos** [comment] 2020-05-17 16:59
Thanks for the PR! Build passed through and I merged it :) This seems to indicate that the issue may be with your installation? Let me know what you think

**Comment by chenrui333** [comment] 2020-05-17 17:46
yeah, pretty interesting, let me try on my side. :)

Thanks for the merge!

**Comment by chenrui333** [comment] 2020-05-17 17:58
I think I probably found the issue (might be python 3 related, the build config is using python 3.7, but we did migrate the formula to use 3.8.2 some time ago).

**Comment by msoos** [comment] 2020-05-17 18:02
Ah, interesting. I actually auto-detect which python to use (2 or 3) so do look into that, it may be an issue with that. I try to use 3 when everything is detected about 3. Otherwise, I fall back to 2. It can do weird things, but I can't find a better way of doing the detection, I want it to compile for both, automatically. So do check that :) Let me know what you found!

**Comment by Gerhood** [comment] 2020-07-12 07:20
I'm running into the same problem using Python 3.7.3

**Comment by msoos** [comment] 2020-07-14 18:07
Hi! I believe this to be an issue on the build end -- the error indicates that a file included by Python itself(!!) is missing a header. Hence it seems that Python development libraries are not correctly/fully installed. Can you please check? If you have a look at TravisCI you will see that the MacOS builds all go through flawlessly. So it seems that I cannot reproduce this issue. Please take a look and get back here :) Thanks!

**Comment by Gerhood** [comment] 2020-08-18 05:55
Hi. It works now for me with Python 3.8.5 (and some OS updates). I cannot tell you why though

**Comment by msoos** [comment] 2020-08-24 23:16
Haha, sounds great! Thanks for all the work helping to debug this, glad that it's all been resolved :) Cheers!

**Closed by msoos** 2020-08-24 23:16 UTC

**Comment by chenrui333** [comment] 2020-08-25 19:52
> Hi. It works now for me with Python 3.8.5 (and some OS updates). I cannot tell you why though

interesting, I will take that and give another shot.
