### ISSUE TITLE
Assert: File: clausecleaner.cpp, Line 61: Expression: solver->value(ws.lit2()) == l_Undef

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#200] opened 2014-07-20 14:02 UTC
File: clausecleaner.cpp, Line 61

Expression: solver->value(ws.lit2()) == l_Undef

Meanwhile seen a few times, with
b72bc4b397192ba55a4ef13c8e7b0dbe9a284fbc (27.05.2014)
and
9b50346ce6e60a997f3dddfb8d04f0bf0564cdb6 (30.06.2014)

Not really reproduceable, but happening from time to time.
Could be the same as #117 (but have not checked if assert in old sources line 101
is now at line 61).

Log output:

c Empty resolvent elimed: 0 T:1.2 T-out: Y
c  #try to eliminate: 1207718
c  #var-elim: 336
c  #T-o: N
c  #T-r: 100.00%
c  #T: 24.96
c [gate] found irred:1 avg-s: 2.0 red: 0 T: 0.81 T-out: Y
c [gate] shorten cl:     0 l-rem:      0 T:    0.25 T-out: N
c [gate] rem cl: 0 avg s: nan T: 0.00 T-out: N
c [gate] eqlit v-rep:   0 T: 0.00

*** 
The above line is last line seen when crash is happening,
so it looks like to happen during "c [clean]". Crash in clausecleaner.cpp
could fit to this. Correct run continues with below lines.
***

c [clean] T: 0.6390 s
c [occur] 1.9810 is overhead
c [v-elim] elimed: 336 / 507241 / 1207718 T: 24.98 s T-out: N

**Comment by msoos** [comment] 2015-04-14 22:10
I cannot reproduce this :( If you can send me a file that sometimes does it, then I can execute that a hundred times and find the fault. Until then, I'm closing this :) Thanks!

**Closed by msoos** 2015-04-14 22:10 UTC
