### ISSUE TITLE
Correct behaviour with multithreads?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#333] opened 2016-04-20 11:23 UTC
```
c [features] numVars 16804...
c clause size stats. size4: 2744 size5: 813 larger: 3654
c   757  168K   16804  7211  412K 11927K    7.67    2.04  1887   24K    58     5  669.82  668.22
c 300-long burst search  learnt units:0 learnt bins: 0 T: 4.66
c [DBclean] marked: 15000 ttl:1518 locked_solver:70 T: 0.04
c [mem] Consolidated memory  old size   21M new size 12279K T: 0.14
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c   784  175K   16804  7211  412K 11927K    7.67    2.04  1971 17844    58     5  663.27  661.18
c   805  182K   16804  7211  412K 11927K    7.67    2.04  2017   24K    59     5  716.66  714.95
c [DBclean] marked: 15000 ttl:3639 locked_solver:32 T: 0.03
c [mem] Consolidated memory  old size   22M new size 12858K T: 0.26
c   861  189K   16804  7211  412K 11927K    7.67    2.04  2126   20K    62     9  604.10  602.19
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c   869  196K   16804  7211  412K 11927K    7.67    2.04  2141   27K    62     9  661.18  659.59
c [DBclean] marked: 15000 ttl:3060 locked_solver:94 T: 0.07
c [mem] Consolidated memory  old size   22M new size 12606K T: 0.15
c   915  203K   16804  7211  412K 11927K    7.67    2.04  2210   22K    62     9  601.89  600.14
c   964  210K   16804  7211  412K 11927K    7.67    2.04  2263   29K    64     9  592.66  591.29
c [DBclean] marked: 15000 ttl:2923 locked_solver:67 T: 0.08
c [mem] Consolidated memory  old size 19385K new size 10781K T: 0.13
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c   970  217K   16804  7211  412K 11927K    7.67    2.04  2333   23K    74     9  601.10  599.20
c [DBclean] marked: 15000 ttl:4455 locked_solver:57 T: 0.07
c [mem] Consolidated memory  old size 19534K new size 12548K T: 0.14
c  1011  224K   16804  7211  412K 11927K    7.67    2.04  2468   20K    79     9  564.25  562.07
c  1057  231K   16804  7211  412K 11927K    7.67    2.04  2530   27K    79     9  565.14  563.47
c [DBclean] marked: 15000 ttl:2979 locked_solver:73 T: 0.06
c [mem] Consolidated memory  old size   20M new size 11365K T: 0.14
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c  1057  238K   16804  7211  412K 11927K    7.67    2.04  2639   21K    79     9  606.94  604.78
c  1110  245K   16804  7211  412K 11927K    7.67    2.04  2714   28K    81     9  608.27  606.54
c [DBclean] marked: 15000 ttl:3270 locked_solver:57 T: 0.07
c [mem] Consolidated memory  old size   20M new size 13397K T: 0.24
c  1154  252K   16804  7211  412K 11927K    7.67    2.04  2859   23K    85     9  622.62  620.45
c [DBclean] marked: 15000 ttl:3269 locked_solver:87 T: 0.08
c [mem] Consolidated memory  old size   22M new size 12097K T: 0.14
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c  1165  259K   16804  7211  412K 11927K    7.67    2.04  2935 19030    88     9  585.02  582.46
c  1189  266K   16804  7211  412K 11927K    7.67    2.04  2975   25K    88     9  630.52  628.42
c [DBclean] marked: 15000 ttl:2917 locked_solver:48 T: 0.08
c [mem] Consolidated memory  old size   20M new size 13511K T: 0.20
c  1233  273K   16804  7211  412K 11927K    7.67    2.04  3076   20K    91     9  624.99  622.38
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c  1286  280K   16804  7211  412K 11927K    7.67    2.04  3140   27K    92     9  607.69  605.70
c Finished thread 7 with result: c [DBclean] marked: l_Undef T-diff: 15000867.19 ttl:
2905 locked_solver:78 T: 0.07
c [mem] Consolidated memory  old size   20M new size 10365K T: 0.19
c  1286  287K   16804  7211  412K 11927K    7.67    2.04  3228   22K    93     9  570.24  567.99
c  1316  294K   16804  7211  412K 11927K    7.67    2.04  3274   29K    94     9  591.02  589.16
c [DBclean] marked: 15000 ttl:3266 locked_solver:36 T: 0.07
c [mem] Consolidated memory  old size 19919K new size 13183K T: 0.19
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c  1362  301K   16804  7211  412K 11927K    7.67    2.04  3430   24K    96     9  590.68  588.46
c --> Executing strategy token: handle-comps
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 6M T: 0.14
c --> Executing strategy token: cache-clean
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.00
c --> Executing strategy token: cache-tryboth
c [bcache]  0-depth ass: 0 BXprop: 0 T: 0.15
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: c Finished thread 5 with result: l_Undef T-diff: 911.13
0 (stamp: 0, cache: 0) T: 3.00 T-out: Y w-visit: 33076
c --> Executing strategy token: intree-probe
c [clean] T: 0.6850 s
c [scc] new: 0 BP 6M T: 0.17
c [clean] T: 0.6460 s
c [vrep] vars 0 lits 0 rem-bin-cls 0 rem-tri-cls 0 rem-long-cls 0 BP 0M T: 1.32
```
Here thread 2 ends...
```
c Finished thread 2 with result: l_Undef T-diff: 919.85
c [intree] Set 0 vars hyper-added: 0 trans-irred::0 trans-red::0 T: 13.03 T-out: Y T-r: -0.00%
c --> Executing strategy token: probe
c [clean] T: 0.7090 s
c [probe] lits : 18.69M act vars: 16.80K BP+HP todo: 960.00M
c [probe] NumProps after perf multi: 480.00M after numcall multi: 667.39M (<- final)
c [probe] 0-depth assigns: 0 bsame: 0 Flit: 0 Visited: 16820/33608(50.0%)
c [probe] probed: 132(0.4%) hyperBin:0 transR-Irred:0 transR-Red:0
c [probe] BP: 388.2M HP: 278.8M T: 4.75 T-out: Y T-r: -0.34%
c [probe] time spent updating cache during probing: 0.0%
c --> Executing strategy token: sub-str-cls-with-bin
c [clean] T: 0.6440 s
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 1.35 T-out: Y T-r: -0.00%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 1
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.24 T-out: N T-r: 77.23%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.75 T-out: Y T-r: -0.02%
c [distill-with-bin-ext] stamp-based lit-rem: 4 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 123003 cl-sub: 1
c [distill-with-bin-ext] cache-based lit-rem: 3328 cl-sub: 0
c [distill-with-bin-ext] T: 0.38 T-out: N T-r: 53.20%
c [distill] cache-based irred--  cl tried     9047 cl-sh     0 cl-rem    0 lit-rem      0 T: 2.10 T-out: Y
c [distill] cache-based   red--  cl tried     6921 cl-sh  1438 cl-rem    2 lit-rem 126335 T: 0.61 T-out: N
c --> Executing strategy token: distill-cls
c Finished thread 3 with result: l_Undef T-diff: 960.91
```
Here thread 3 ends...
```
c [distill] longirred tried: 3319/7211 cl-r:0 lit-r:0 T: 3.26 T-out: Y T-r: 100.04%
c [distill] tri+long useful: 0/3319/7211 lits-rem: 0 0-depth-assigns: 0 T: 4.05 T-out: Y
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 6M T: 0.12
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 2 (stamp: 0, cache: 2) T: 1.59 T-out: Y w-visit: 32105
c --> Executing strategy token: str-impl
c [impl str] lit bin: 0 lit tri: 0 (by tri: 0) (by stamp: 0) set-var: 0 T: 4.27 T-out: N T-r: 14.82% w-visit: 34112
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 1.22 T-out: Y w-visit: 32154
c --> Executing strategy token: str-impl
c --> Executing OCC strategy token(s): 'occ-backw-sub-str,occ-clean-implicit,occ-bve,occ-bva,occ-xor,'
c [clean] T: 0.5650 s
c [simp] mem usage for occur      2 MB
c [simp] Not linked in 0/7211 (0.00 %)
c [simp] mem usage for occur      3 MB
c [simp] Not linked in 174/3431 (5.07 %)
c Mem for watch alloc      : 285         MB (0.00      %)
c Mem for watch array      : 0           MB (0.00      %)
c --> Executing OCC strategy token: occ-backw-sub-str
c [sub] tri upI: 1530 subs w bin: 0 str w bin: 0 subs w tri: 0 str w tri: 0 tried: 2453389 str: 0 0-depth ass: 0 T: 1.42 T-out: Y T-r: -0.00%
c [sub] rem cl: 202 tried: 390280/39028 (1000.0%) T: 0.99 T-out: N T-r: 52.05%
c [str] sub: 0 str: 53 tried: 117084/39028 (300.0)  T: 0.58 T-out: N T-r: 60.77%
c [occ-substr] sub_str_with sub: 0 str: 0 0-depth ass: 0 T: 0.00 T-out: N T-r: 100.00%
c --> Executing OCC strategy token: occ-clean-implicit
c --> Executing OCC strategy token: occ-bve
c Empty resolvent elimed: 0 T: 0.01 T-out: N
c [occ-substr] sub_str_with sub: 0 str: 0 0-depth ass: 0 T: 0.00 T-out: N T-r: 100.00%
c [occ-bve] process impls_sub_lits  T: 1.95
c [occ-bve] iter v-elim 0
c  #try to eliminate: 16804
c  #var-elim: 0
c  #T-o: N
c  #T-r: 93.90%
c  #T: 4.58
c [occur] 3.44 is overhead
c [occur] link-in T: 3.44 cleanup T: 0.00
c --> Executing OCC strategy token: occ-bva
c --> Executing OCC strategy token: occ-xor
c [impl str] lit bin: 0 lit tri: 0 (by tri: 0) (by stamp: 0) set-var: 0 T: 4.45 T-out: N T-r: 14.47% w-visit: 34112
c --> Executing strategy token: cache-clean
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.00
c --> Executing strategy token: sub-str-cls-with-bin
c [clean] T: 0.6030 s
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 1.51 T-out: Y T-r: -0.01%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.08 T-out: N T-r: 83.01%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.48 T-out: Y T-r: -0.04%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 2858 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 49 cl-sub: 0
c [distill-with-bin-ext] T: 0.17 T-out: N T-r: 65.60%
c [distill] cache-based irred--  cl tried     8894 cl-sh     0 cl-rem    0 lit-rem      0 T: 1.99 T-out: Y
c [distill] cache-based   red--  cl tried     6546 cl-sh    39 cl-rem    0 lit-rem   2907 T: 0.25 T-out: N
c --> Executing strategy token: distill-cls
c [distill] longirred tried: 1504/7211 cl-r:0 lit-r:0 T: 2.05 T-out: Y T-r: 100.08%
c [distill] tri+long useful: 0/1504/7211 lits-rem: 0 0-depth-assigns: 0 T: 2.05 T-out: Y
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 6M T: 0.10
c --> Executing strategy token: check-cache-size
c --> Executing strategy token: renumber
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.00
c [consolidate] T: 0.00
c clause size stats. size4: 2744 size5: 813 larger: 3654
c 300-long burst search  learnt units:0 learnt bins: 0 T: 0.23
c [DBclean] marked: 15000 ttl:369 locked_solver:30 T: 0.02
c [mem] Consolidated memory  old size 19784K new size 8200K T: 0.10
c  1414  308K   16804  7211  412K 11927K    7.67    2.04  3308 16521   126     9  436.55  433.62
c  1414  315K   16804  7211  412K 11927K    7.67    2.04  3334   23K   126     9  536.96  534.28
c [DBclean] marked: 15000 ttl:4453 locked_solver:62 T: 0.03
c [mem] Consolidated memory  old size 19296K new size 13471K T: 0.10
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c  1440  322K   16804  7211  412K 11927K    7.67    2.04  3421 19770   128     9  578.16  574.79
c  1480  329K   16804  7211  412K 11927K    7.67    2.04  3481   26K   128     9  579.04  576.43
c [DBclean] marked: 15000 ttl:2644 locked_solver:22 T: 0.03
c [mem] Consolidated memory  old size 19515K new size 9914K T: 0.09
c  1532  336K   16804  7211  412K 11927K    7.67    2.04  3592   21K   132     9  479.70  477.00
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c  1549  343K   16804  7211  412K 11927K    7.67    2.04  3635   28K   135     9  545.93  543.47
c [DBclean] marked: 15000 ttl:3158 locked_solver:22 T: 0.03
c [mem] Consolidated memory  old size 19454K new size 12328K T: 0.11
c  1549  350K   16804  7211  412K 11927K    7.67    2.04  3705   23K   137     9  675.56  671.91
c  1598  357K   16804  7211  412K 11927K    7.67    2.04  3761   29K   143     9  654.73  651.80
c [DBclean] marked: 15000 ttl:3043 locked_solver:58 T: 0.03
c [mem] Consolidated memory  old size   22M new size 14883K T: 0.11
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c  1637  364K   16804  7211  412K 11927K    7.67    2.04  3857   24K   144     9  652.21  648.77
c [DBclean] marked: 15000 ttl:2946 locked_solver:26 T: 0.03
c [mem] Consolidated memory  old size   22M new size 10023K T: 0.10
c  1687  371K   16804  7211  412K 11927K    7.67    2.04  3953 19694   145     9  458.31  455.37
c  1700  378K   16804  7211  412K 11927K    7.67    2.04  3983   26K   145     9  583.02  580.11
c [DBclean] marked: 15000 ttl:3264 locked_solver:82 T: 0.06
c [mem] Consolidated memory  old size   21M new size 15097K T: 0.08
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c  1700  385K   16804  7211  412K 11927K    7.67    2.04  4006   21K   145     9  725.17  720.88
c  1743  392K   16804  7211  412K 11927K    7.67    2.04  4050   28K   147     9  704.45  701.12
c [DBclean] marked: 15000 ttl:3185 locked_solver:39 T: 0.02
c [mem] Consolidated memory  old size   24M new size 14907K T: 0.11
c  1791  399K   16804  7211  412K 11927K    7.67    2.04  4159   23K   149     9  637.43  633.86
```
Other are still running...

**Comment by msoos** [comment] 2016-05-05 19:23
It's a bit strange that it ended with l_Undef. Did you set a limit? It could have been that the limit is reached earlier in some threads than in others. Limits (time/conflicts) don't really work well in multi-threaded mode. I'll set this as a feature request to fix threads' limits. But to be honest, I don't think I will have time to do this in the next couple of months, sorry. Do you really-really need this?

**Comment by capiman** [comment] 2016-05-05 20:15
> Do you really-really need this?

No, it is no major point to solve. If it is easy to fix, it would be nice. If not, it does not matter
and entry can be closed.

**Comment by msoos** [comment] 2016-05-17 22:26
The problem is that maxconfl will stop at different parts for different threads. So maxconfl is not very useful in a multi-thread context. Unfortunately, there are no real good solutions to this. Using timeout may work, but in multi-thread it might also partially misbehave :( This is unfortunately a WONTFIX as I don't have time for this :(

**Closed by msoos** 2016-05-17 22:26 UTC
Labels: enhancement
