### ISSUE TITLE
Incorrect Full Model

### ISSUE THREAD

**Issue by AL-JiongYang** [msoos/cryptominisat#736] opened 2023-10-18 15:57 UTC
CMS returned an incorrect full model on the attached [instance](https://drive.google.com/file/d/1VhOiNBAjQCriqkux_OFRCo1LmO933JHq/view?usp=share_link) when used as the underlying SAT solver of [ApproxMC](https://github.com/meelgroup/approxmc). Thanks Yong Kiam (@tanyongkiam) for reporting the error!

To reproduce the error:
we compiled ApproxMC (8ab5426e690aeb64469904c6a425a179a8da78c9) with CMS (c6ced12f9daaa67d0386fafc227581af0a0dd7f9) and ran the following command line.
`approxmc --arjun 0 blasted_case12.cnf.gz.no_w.cnf.gz`
After some time, CMS started to return an incorrect full model: 
`... -42 ... 540 541 ...`
which falsifies the following clause appearing in the input formula at Line 793.
`-540 -541 42 0`
ApproxMC only uses the model projected on the sampling set, so the error may not affect the correctness of ApproxMC. We discovered this error when we modified ApproxMC to ask for the full model from CMS, i.e., the model on all variables.

We found that the error appears after adding the first XOR constraint in ApproxMC and disappears if we disable the simplification. Specifically, the error disappears when disabling either BVE or XOR-detach. 

Moreover, the bug always follows adding an XOR constraint. If we don't add XOR in ApproxMC, CMS never gives a wrong solution in this instance. However, if we start ApproxMC with even a single XOR constraint, i.e. hashCount=1, CMS outputs a wrong solution very soon. On the other hand, It seems that the variables inside the XOR constraint are not the primary cause because we tried different random seeds, i.e., different XOR constraints, and they all ended up with a wrong solution very soon given an XOR constraint. 

However, we found it difficult to reproduce the error directly in CMS. Even though we added an XOR constraint to the input formula, enabled BVE and XOR detach, set the same sampling set, and iteratively asked for one thousand solutions, CMS still gave the correct ones.

Finally, we dumped the internal CNF from CMS when we got the wrong solution, and the internal CNF still contradicts the solution we obtained. Therefore, the error may arise from translating the internal assignments to the external ones when considering the eliminated variables (related to XOR).

**Comment by msoos** [comment] 2023-10-18 19:25
Thank you so much! This  has indeed been confirmed via `0301e8c7f44edb1bc2e24352e6c10ff5e79a6139` commit in ApproxMC, that added the `--debug` flag that checks for all solutions. Thanks again, sad this slipped through. I'll fix it via a rather convoluted, but in the end, easier-to-verify route by removing some of the complexity in the underlying XOR manipulation system.

Again, thanks for the report, it's really useful. The fix is on the way :)

Mate

**Comment by msoos** [comment] 2024-01-14 14:18
This has finally been fixed in the branch `fixing-xor-cutting-frat-xor-plus`. I am closing this issue because it is known fixed and will be released in approx a week's time.

**Closed by msoos** 2024-01-14 14:18 UTC
