### ISSUE TITLE
CMSat::ClauseCleaner::clean_binary_implicit assertion failed

### ISSUE THREAD

**Issue by maxzinkus** [msoos/cryptominisat#557] opened 2019-05-27 21:20 UTC
```
cryptominisat5: /home/ubuntu/cryptominisat/src/clausecleaner.cpp:64: void CMSat::ClauseCleaner::clean_binary_implicit(CMSat::Watched&, CMSat::Watched*&, CMSat::Lit): Assertion `solver->value(lit) == l_Undef' failed.
Aborted (core dumped)
```

[cms_error_-6.cnf.txt](https://github.com/msoos/cryptominisat/files/3224979/cms_error_-6.cnf.txt)

**Comment by maxzinkus** [comment] 2019-05-27 21:31
Not sure what this means or why it's occurring. The backtrace comes up through `CMSat::Searcher`

**Comment by msoos** [comment] 2019-05-27 21:39
Hi,

Thanks for the bug report! I need to know:
- What is your GIT SHA version and/or what version you downloaded
- What is the input you ran
- How it was compiled (the first 3-4 lines of CryptoMiniSat)
- Whether it can be reproduced
- What input you can and with what options

Then I'll reproduce the bug and fix it :) Thanks again, and looking forward to all this information so I can debug! Otherwise, I cannot reproduce and cannot fix :( Thanks in advance,

Mate

**Comment by maxzinkus** [comment] 2019-05-27 21:48
* git: *devel* branch: 517503c0e0c25c33c4f9eb78fd58c8a1d0c7bcb1
* The input is the cnf.txt file linked in the initial posting above.
* It can be reproduced consistently.

```
c CryptoMiniSat version 5.6.8
c CMS Copyright Mate Soos (soos.mate@gmail.com)
c CMS SHA revision 517503c0e0c25c33c4f9eb78fd58c8a1d0c7bcb1
c CMS is GPL licensed due to M4RI being linked. Build without M4RI to get MIT version
c Using Yalsat by Armin Biere, see Balint et al. Improving implementation of SLS solvers [...], SAT'14
c Using WalkSAT by Henry Kautz, see Kautz and Selman Pushing the envelope: planning, propositional logic, and stochastic search, AAAI'96,
c Using code from 'When Boolean Satisfiability Meets Gauss-E. in a Simplex Way'
c       by C.-S. Han and J.-H. Roland Jiang in CAV 2012. Fixes by M. Soos
c CMS compilation env CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -ggdb3 -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -pedantic | COMPILE_DEFINES =  -DUSE_GAUSS -DBOOST_TEST_DYN_LINK -DUSE_ZLIB -DYALSAT_FPU -DUSE_M4RI | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND =  | ENABLE_TESTING = OFF | M4RI_FOUND = TRUE | NOM4RI = OFF | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE = /usr/bin/python2.7 | PYTHON_LIBRARY = /usr/lib/x86_64-linux-gnu/libpython2.7.so | PYTHON_INCLUDE_DIRS = /usr/include/python2.7 | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | compilation date time = May 26 2019 23:13:23
```

Thank you for the prompt response as always!

**Comment by maxzinkus** [comment] 2019-05-28 15:31
Repros with `cryptominsat5 input.cnf` and also `cryptominisat5 --maxxorsize 8 --maxnummatrixes 100`

**Comment by msoos** [comment] 2019-05-28 17:02
Hi,

I am really confused, I was an idiot, I wrote a comment yesterday and forgot to send you. Please don't use the `devel` branch. Please use the `master` branch. It is probably even faster than the `devel`. It should have none of these issues. If it still does, please re-open the issue! :) Thanks!

**Comment by maxzinkus** [comment] 2019-05-28 17:06
This issue is still an issue in the devel branch and thus should probably stay open, right?

Either way, I can't switch now because I have long-running tests executing.

**Comment by msoos** [comment] 2019-05-28 17:15
This is almost surely a duplicate of #558 so let's discuss there.

**Comment by msoos** [comment] 2019-05-28 17:43
This is not a duplicate, re-opening.

**Comment by msoos** [comment] 2019-05-28 19:36
First, an apology is in order. This is indeed a bug and now I will be working very hard to make sure that I can fuzz this kind of issue. The problem is that you have multiple matrices and this has not been fuzzed. So you bumped into 3 separate problems regarding this: #552, #558 and this. I am extremely sorry that you had such a bad experience. All 3 are completely valid and affect every branch. So, it was very valuable that you reported to me, thank you so much! I have now fixed this and #558. I will think about how to fuzz thing thing. To be honest, I would _very_ much welcome your problem generator, because it seems to spit out amazingly good problems that I cannot seem to generate. All my generators have a single matrix, and **all** 3 bugs you found were about multiple matrices interacting.

As a thank-you, I have put your name and a thank you note into both commits. Thank you so much.

So both this and #558 are now solved.

**Closed** 2019-05-28 19:36 UTC

**Comment by msoos** [comment] 2019-05-28 19:38
Please let me know if this or anything like this re-occurs. This should now be solved in both `devel` and `master`.

I usually fuzz this thing to hell and it's extremely rare to have any bugs. But I didin't fuzz multi-matrix :( Sorry and thank you again for your patience.

**Comment by maxzinkus** [comment] 2019-05-28 22:35
Will do, and thank you for the fast responses as always.
