### ISSUE TITLE
Windows build issues

### ISSUE THREAD

**Issue by andrewjlawrence** [msoos/cryptominisat#383] opened 2017-03-11 20:43 UTC
I built the full version of CMS on Windows and made some observations.
1) Running: 
    $ cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015 Win64" -DSTATICCOMPILE=ON
    $ msbuild INSTALL.vcxproj
    causes a debug build to occur even though release has been specified.
2) The check for boost in the cmake file seems to look for the dynamic libraries. I think the "set(Boost_USE_STATIC_LIBS ON)" command should be added before searching for boost.
3) Boost needs to be built with the "link=static" and "runtime-link=static" options. Should this be noted somewhere?
4) When building the full version of the solver a "output name same as input error" occurs. This can be fixed by setting Configuration Properties/Linker/Advanced/Import Library field to empty (I am not sure how this can be done in cmake).   
5) The minimum version of Visual Studio needs updating. The cmake files imply that CMS can be built with VS 2010 however this is not the case as it only has partial support for C++ 11.

**Comment by msoos** [comment] 2017-03-12 13:03
Wow, that's great that you managed to build the full version!! I will try to make sure AppVeyor can build it too and so I can package it! That'd be really good. I already release full binary static version for Linux, it should be done for Windows, too. I'll go through these and try to make them all work in AppVeyor. I'll update this once it's done :) Thanks again!

**Comment by andrewjlawrence** [comment] 2017-03-12 16:56
When I say full I mean I built it with boost program options. I haven't got the python bindings to build yet but I will give that a go at some point.

**Comment by msoos** [comment] 2017-03-13 20:39
That's full enough :) I'm playing with AppVeyor now, fingers crossed. It'll take a while but I think it'll work eventually.

**Comment by msoos** [comment] 2017-03-18 12:31
I have made a LOT of progress. I can build it with boost and it works in static mode, so it's great! However, when trying to make it work with zlib, I get:

```
C:\projects\cryptominisat\src\main.cpp(124): error C2971: 'StreamBuffer': template parameter 'C': 'gz_read': a variable with non-static storage duration cannot be used as a non-type argument [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\streambuffer.h(42): note: see declaration of 'StreamBuffer'
  C:\projects\cryptominisat\src\main.cpp(56): note: see declaration of 'gz_read'
C:\projects\cryptominisat\src\main.cpp(172): error C2971: 'StreamBuffer': template parameter 'C': 'gz_read': a variable with non-static storage duration cannot be used as a non-type argument [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\streambuffer.h(42): note: see declaration of 'StreamBuffer'
  C:\projects\cryptominisat\src\main.cpp(56): note: see declaration of 'gz_read'
```

How did you fix this? (this is in `multilevel_maple` branch). I think this is all I need now to have a full static binary release :) Thanks in advance!!

**Comment by a1880** [comment] 2017-03-18 16:59
It might help to assign the fileName.c_str() to a char pointer variable before calling gz_read(). Haven't  tried it myself, though.  Thumbs up for your progress towards a Windows build

**Comment by msoos** [comment] 2017-03-18 17:07
This is a bit more meta than that :) The variable here is gz_read(), not what it's called with. I have it as a static function, and it compiles under gcc and clang, but not under Windows. It doesn't see it as static in memory :S

**Comment by msoos** [comment] 2017-03-18 20:11
Well, this has been a wild ride but it now builds, all bells and whistles, with boost and zlib under Windows: https://ci.appveyor.com/project/msoos/cryptominisat/ This is currently in the multilevel_maple branch, but that will be merged into master. Thanks a lot for the feedback, it was cool!

**Comment by a1880** [comment] 2017-03-19 15:13
I was so fed up with zlib that I implemented a dummy and have been using it without problems ever since:

/*---- zlib.h ----------------------------------------------------------------*/

#pragma once

//
//  dummy zlib.h
//

#include <stdio.h>

typedef FILE *gzFile;

int gzclose(gzFile file);
gzFile gzdopen(int fd, const char *mode);
gzFile gzopen(const char *path, const char *mode);
int gzread(gzFile file, void *buf, unsigned int len);

/*---- zlibDummy.cpp ----------------------------------------------------------------*/

//
//  zlibDummy.cpp
//

#include <zlib.h>

int gzclose(gzFile file)
{
    int ret = fclose(file);

    return ret;
}

gzFile gzdopen(int fd, const char *mode)
{
    gzFile gz = _fdopen(fd, mode);

    return gz;
}

gzFile gzopen(const char *path, const char *mode)
{
    gzFile gz = fopen(path, mode);

    return gz;
}

int gzread(gzFile file, void *buf, unsigned int len)
//  On success, gzread() shall return the number of bytes decompressed into buf. 
//  If gzread() returns 0, either the end-of-file has been reached or an underlying 
//  read error has occurred. Applications should use gzerror() or gzeof() to determine 
//  which occurred. On other errors, gzread() shall return a value less than 0 and 
//  and applications may examine the cause using gzerror().
{
    int ret = fread(buf, 1, len, file);

    return ret;
}

**Comment by a1880** [comment] 2017-03-19 23:17
The latest Windows build of full cryptominisat5 requires zlib.dll on the Windows search path. It would be handy to get this linked in statically, because it is non-trivial to provide the right zlib.dll.

**Comment by msoos** [comment] 2017-03-20 00:35
That is an issue.  It should use the static one. I'll look into this. You are using the `multilevel_maple` branch, right?

**Comment by a1880** [comment] 2017-03-20 07:55
yes, that's true

**Comment by msoos** [comment] 2017-03-23 21:16
@a1880 Can you please try to see how we could compile zlib in statically? The Boost is statically compiled in, only zlib is not (apparently). The `README.md` on the multilevel_maple branch tells how it's exactly done for both Boost and zlib, so you could try debugging there, if you have a bit of time? Thanks! You can see a bit more about how it's done in the `appveyor.yml file` again in the `multilevel_maple` branch. Thanks again :)

**Comment by a1880** [comment] 2017-03-23 22:37
Hi Mate, zlib can be a static of a dynamic library. In both cases, you link a *.lib file. If you take the wrong one, a *.dll is required at runtime. I found a recipe to compile zlib under Visual Studio 2015: http://www.chemformatter.com/build-with-visual-studio-2015/zlib   A zconf.h file is created to set the machine specific parameters. I send you a collection of the files via mail.

**Comment by msoos** [comment] 2017-03-23 22:56
If you look at my appveyor output (or follow the README.md and check the output), it compiles the static library, too. It just links in the non-static one :S Probably the FindZlib package from cmake is wrongly configured and it picks the dynamic library. That needs to be fixed, I think.

**Comment by a1880** [comment] 2017-03-24 10:37
I have experimented with the zlib build scripted in appveyor.yml. It results in zlib.lib and zlibstatic.lib. My understanding is that cmake FindZlib just returns the library directory ZLIB_LIB_DIR rather than the library name. I haven't found yet where zlib.lib has to be replaced with zlibstatic.lib. The cmake variable is ZLIB_LIBRARY. FindZlib does set this to zlib.lib, which is not what we want.

**Comment by msoos** [comment] 2017-03-26 16:14
Hi Axel, Can you please check https://ci.appveyor.com/project/msoos/cryptominisat/build/1.0.231 I'm getting weird stuff with linking if I replace zlib.lib with staticzlib.lib. Thanks!

**Comment by a1880** [comment] 2017-03-26 17:51
My first impression is that the zlib binaries might not be compatibel with the cryptominisat object files because zlib is compiled as C rather than C++. I once had a similar effect with m4ri and resorted to a cplusplus bracket around the include file. 

In m4ri.h, the construction is

```
#if defined(__cplusplus) && !defined (_MSC_VER)
extern "C" {
#endif

#include <m4ri/mzp.h>
#include <m4ri/mzd.h>
#include <m4ri/brilliantrussian.h>
#include <m4ri/strassen.h>
#include <m4ri/mp.h>  
#include <m4ri/graycode.h>
#include <m4ri/parity.h>
#include <m4ri/triangular.h>
#include <m4ri/triangular_russian.h>
#include <m4ri/ple.h>
#include <m4ri/ple_russian.h>
#include <m4ri/solve.h>
#include <m4ri/echelonform.h>
#include <m4ri/io.h>
#include <m4ri/djb.h>

#if defined(__cplusplus) && !defined (_MSC_VER)
}
#endif

```

There seems to be a known issue with the calling conventions of zlib as described here: 
http://www.tannerhelland.com/5076/compile-zlib-winapi-wapi-stdcall/
So, it might be the easiest way to use a zlib1.2.5 version suitable for STDCALL.
Sorry, that the Windows port is such a nuisance, but I am just the messenger again.

**Comment by a1880** [comment] 2017-03-27 12:26
I have found the following (, but haven't tried it yet):

Define the ZLIB_WINAPI macro before including "zlib.h", when building both the DLL and the user application. The ZLIB_WINAPI macro will switch on the WINAPI (STDCALL) convention.

**Comment by msoos** [comment] 2017-05-03 20:58
Thanks to this thread, the Windows build has been fixed, see https://ci.appveyor.com/project/msoos/cryptominisat Thanks to everyone for their great input, it's been a nice ride. You can download the statically linked, fully functional Windows binary from https://ci.appveyor.com/project/msoos/cryptominisat/build/artifacts (i.e. the "Artifacts" section of the previous link). I hope it helps!

Thanks again for all the feedback! Please open a new issue for any outstanding items!

**Closed by msoos** 2017-05-03 20:58 UTC
Labels: enhancement
