### ISSUE TITLE
Under MinGW, "make install" does not copy dll files

### ISSUE THREAD

**Issue by Topsii** [msoos/cryptominisat#417] opened 2017-08-14 16:56 UTC
From [this issue](https://github.com/msoos/cryptominisat/issues/401):
The DLLs are not copied into C:\Program Files\cryptominisat5\bin
This happens when compiling with MinGW.

**Comment by msoos** [comment] 2017-08-24 20:21
This is the code that's responsible for installing the library:

```
install(TARGETS libcryptominisat5
    EXPORT ${CRYPTOMINISAT5_EXPORT_NAME}
    LIBRARY DESTINATION "${CMAKE_INSTALL_PREFIX}/${LIBDIR}"
    ARCHIVE DESTINATION "${CMAKE_INSTALL_PREFIX}/${LIBDIR}"
    PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_PREFIX}/${INCLUDEDIR}/cryptominisat5"
)
```

Can you please give me an output for the install? How do you execute it after building? I build like:

```
- cmake --build . --config %CONFIGURATION%
```

but I don't understand how do you install. Please explain and then I can test :) Thanks!

**Comment by Topsii** [comment] 2017-08-26 00:00
CMake generates Make files that support the install target:

    C:\msoos\cryptominisat\build>stack exec -- make install
    [  2%] Built target tablestruct
    [ 83%] Built target libcryptominisat5
    [ 87%] Built target ipasircryptominisat5
    Copying cryptominisat_c.h to C:/msoos/cryptominisat/build/include/cryptominisat5
    Copying cryptominisat.h to C:/msoos/cryptominisat/build/include/cryptominisat5
    Copying solvertypesmini.h to C:/msoos/cryptominisat/build/include/cryptominisat5
    [ 87%] Built target CopyPublicHeaders
    [ 91%] Built target cryptominisat5_simple
    [100%] Built target cryptominisat5
    Install the project...
    -- Install configuration: "RelWithDebInfo"
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/cmake/cryptominisat5/cryptominisat5Config.cmake
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/cmake/cryptominisat5/cryptominisat5Targets.cmake
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/cmake/cryptominisat5/cryptominisat5Targets-relwithdebinfo.cmake
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/libipasircryptominisat5.a
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/libcryptominisat5win.a
    -- Installing: C:/Program Files (x86)/cryptominisat5/include/cryptominisat5/cryptominisat_c.h
    -- Installing: C:/Program Files (x86)/cryptominisat5/include/cryptominisat5/cryptominisat.h
    -- Installing: C:/Program Files (x86)/cryptominisat5/include/cryptominisat5/solvertypesmini.h
    -- Installing: C:/Program Files (x86)/cryptominisat5/bin/cryptominisat5_simple.exe
    -- Installing: C:/Program Files (x86)/cryptominisat5/bin/cryptominisat5.exe

**Comment by msoos** [comment] 2017-08-30 21:01
Hmmm... so only the .dll.a is copied, but not the DLL? Does the executable complain that it cannot find the DLL or the DLL.a? What does the executable say is missing?

**Comment by msoos** [comment] 2017-08-30 21:03
Also, how did you configure it? Was it just a "cmake ." or did you add e.g. -DSTATICCOMPILE=ON? Any other flags?

**Comment by Topsii** [comment] 2017-08-31 00:42
> Hmmm... so only the .dll.a is copied, but not the DLL?

Exactly!
Hence the problem only exists with STATICCOMPILE disabled.
I also disabled the python interface. 

    mkdir build
    cd build
    stack exec -- cmake -G "MSYS Makefiles" -DIPASIR=ON -DENABLE_PYTHON_INTERFACE=OFF ..

As I said previously:

> It works once I copy it into the same folder as the executable. Otherwise it complains that libcryptominisat5win.dll is missing in case of MinGW or cryptominisat5win.dll in case of MSVC. A file with this name is created in the cmsat5-src directory in the build directory, though this directory needs to be added to the path environment variable to be searched when executing cryptominisat5.exe. Same for ipasircryptominisat5.

Currently the dll file needs to be either copied from the cmsat5-src directory into the install directory manually, or the cmsat5-src directory needs to be added to the path environment variable.

I would expect the dll files to be installed, too.

**Comment by msoos** [comment] 2018-01-08 22:02
I'll mark this as the duplicate of https://github.com/msoos/cryptominisat/issues/418 I think I have got this one fixed once that is fixed. And I think that might be fixed too :) Can you please check?

**Closed by msoos** 2018-01-08 22:02 UTC

**Comment by Topsii** [comment] 2018-01-09 21:42
Looks good, but the .dll files should be copied to .../bin/ instead of .../lib/

MinGW:

    -- Install configuration: "RelWithDebInfo"
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/cmake/cryptominisat5/cryptominisat5Config.cmake
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/cmake/cryptominisat5/cryptominisat5Targets.cmake
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/cmake/cryptominisat5/cryptominisat5Targets-relwithdebinfo.cmake
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/libipasircryptominisat5.dll.a
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/libipasircryptominisat5.dll
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/libcryptominisat5win.dll.a
    -- Installing: C:/Program Files (x86)/cryptominisat5/lib/libcryptominisat5win.dll
    -- Installing: C:/Program Files (x86)/cryptominisat5/include/cryptominisat5/cryptominisat_c.h
    -- Installing: C:/Program Files (x86)/cryptominisat5/include/cryptominisat5/cryptominisat.h
    -- Installing: C:/Program Files (x86)/cryptominisat5/include/cryptominisat5/solvertypesmini.h
    -- Installing: C:/Program Files (x86)/cryptominisat5/bin/cryptominisat5_simple.exe
    -- Installing: C:/Program Files (x86)/cryptominisat5/bin/cryptominisat5.exe

MSVC:

    -- Install configuration: "Debug"
    -- Installing: C:/Program Files/cryptominisat5/CMake/cryptominisat5Config.cmake
    -- Installing: C:/Program Files/cryptominisat5/CMake/cryptominisat5Targets.cmake
    -- Installing: C:/Program Files/cryptominisat5/CMake/cryptominisat5Targets-debug.cmake
    -- Installing: C:/Program Files/cryptominisat5/lib/ipasircryptominisat5.lib
    -- Installing: C:/Program Files/cryptominisat5/lib/ipasircryptominisat5.dll
    -- Installing: C:/Program Files/cryptominisat5/lib/cryptominisat5win.lib
    -- Installing: C:/Program Files/cryptominisat5/lib/cryptominisat5win.dll
    -- Installing: C:/Program Files/cryptominisat5/include/cryptominisat5/cryptominisat_c.h
    -- Installing: C:/Program Files/cryptominisat5/include/cryptominisat5/cryptominisat.h
    -- Installing: C:/Program Files/cryptominisat5/include/cryptominisat5/solvertypesmini.h
    -- Installing: C:/Program Files/cryptominisat5/bin/cryptominisat5_simple.exe
