### ISSUE TITLE
Could not build 5.11.14 on Linux without -DONLY_SIMPLE=ON

### ISSUE THREAD

**Issue by mister-walter** [msoos/cryptominisat#734] opened 2023-10-02 15:52 UTC
I'm on Arch Linux (Clang 16, cmake 3.27.6) and could not get a successful cmake run without adding `-DONLY_SIMPLE=ON`.

My cmake invocation was:
`cmake ../ -DIPASIR=ON -DSTATICCOMPILE=OFF -DSTATS=OFF -DNOVALGRIND=ON -DENABLE_TESTING=OFF`

The relevant output is:
```
-- Configuring done (7.0s)
CMake Error at CMakeLists.txt:544 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<TARGET_FILE:cryptominisat5-bin>

  No target "cryptominisat5-bin"


CMake Error at CMakeLists.txt:544 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<TARGET_FILE:cryptominisat5-bin>

  No target "cryptominisat5-bin"


CMake Error at CMakeLists.txt:544 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<TARGET_FILE:cryptominisat5-bin>

  No target "cryptominisat5-bin"


CMake Error at CMakeLists.txt:544 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<TARGET_FILE:cryptominisat5-bin>

  No target "cryptominisat5-bin"


-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    NOVALGRIND


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

The `cryptominisat5-bin` target is mentioned in the Linux manpage generation part of CMakeLists.

I'm not sure if the `cryptominisat5-bin` target is something that should be automatically generated, or something that once was defined but now is not? In the meantime, adding the `ONLY_SIMPLE` option works, as it results in the manpage generation section not being run.

**Comment by msoos** [comment] 2023-10-02 16:04
Good point. I’ll fix it later. It needs a man page generator currently.

**Comment by msoos** [comment] 2023-10-02 16:05
*later today

**Comment by msoos** [comment] 2023-10-02 22:51
Hi,

So something is very off here. It works for me like a charm. Please copy-paste the *full* output of cmake. Please clear the `build` directory before. Basically:

```
rm -rf build
mkdir build
cmake ../ -DIPASIR=ON -DSTATICCOMPILE=OFF -DSTATS=OFF -DENABLE_TESTING=OFF 
```

(I removed the `NOVALGRIND`, it's not supported anymore and I removed it from the README as well). That should work as far as I can see. I thought the manpage generator was not guarded by a test, but it is guarded. So something is off.

I have the same version of cmake. Please provide the **full** output, so I can debug. Thanks,

Mate

**Comment by mister-walter** [comment] 2023-10-02 23:18
```
$ cmake ../ -DIPASIR=ON -DSTATICCOMPILE=OFF -DSTATS=OFF -DENABLE_TESTING=OFF 
-- The CXX compiler identification is Clang 16.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- LIB directory is ''
-- BIN directory is ''
-- You can choose the type of build, options are:Debug;Release;RelWithDebInfo;MinSizeRel
-- Doing a RelWithDebInfo build
-- The C compiler identification is Clang 16.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- tbuddy not found, not compiling with tbuddy-based GJ FRAT proofs
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- build type is RelWithDebInfo
-- Performing Test HAVE_FLAG_-fvisibility=hidden
-- Performing Test HAVE_FLAG_-fvisibility=hidden - Success
-- Performing Test HAVE_FLAG_-Wall
-- Performing Test HAVE_FLAG_-Wall - Success
-- Performing Test HAVE_FLAG_-Wextra
-- Performing Test HAVE_FLAG_-Wextra - Success
-- Performing Test HAVE_FLAG_-Wunused
-- Performing Test HAVE_FLAG_-Wunused - Success
-- Performing Test HAVE_FLAG_-Wsign-compare
-- Performing Test HAVE_FLAG_-Wsign-compare - Success
-- Performing Test HAVE_FLAG_-fno-omit-frame-pointer
-- Performing Test HAVE_FLAG_-fno-omit-frame-pointer - Success
-- Performing Test HAVE_FLAG_-Wtype-limits
-- Performing Test HAVE_FLAG_-Wtype-limits - Success
-- Performing Test HAVE_FLAG_-Wuninitialized
-- Performing Test HAVE_FLAG_-Wuninitialized - Success
-- Performing Test HAVE_FLAG_-Wno-deprecated
-- Performing Test HAVE_FLAG_-Wno-deprecated - Success
-- Performing Test HAVE_FLAG_-Wstrict-aliasing
-- Performing Test HAVE_FLAG_-Wstrict-aliasing - Success
-- Performing Test HAVE_FLAG_-Wpointer-arith
-- Performing Test HAVE_FLAG_-Wpointer-arith - Success
-- Performing Test HAVE_FLAG_-Wheader-guard
-- Performing Test HAVE_FLAG_-Wheader-guard - Success
-- Performing Test HAVE_FLAG_-Wformat-nonliteral
-- Performing Test HAVE_FLAG_-Wformat-nonliteral - Success
-- Performing Test HAVE_FLAG_-Winit-self
-- Performing Test HAVE_FLAG_-Winit-self - Success
-- Performing Test HAVE_FLAG_-Wparentheses
-- Performing Test HAVE_FLAG_-Wparentheses - Success
-- Performing Test HAVE_FLAG_-Wunreachable-code
-- Performing Test HAVE_FLAG_-Wunreachable-code - Success
-- Performing Test HAVE_FLAG_-g
-- Performing Test HAVE_FLAG_-g - Success
-- Performing Test HAVE_FLAG_-Wno-class-memaccess
-- Performing Test HAVE_FLAG_-Wno-class-memaccess - Failed
-- Performing Test HAVE_FLAG_-mpopcnt
-- Performing Test HAVE_FLAG_-mpopcnt - Success
-- Performing Test HAVE_FLAG_-msse4.2
-- Performing Test HAVE_FLAG_-msse4.2 - Success
-- Performing Test HAVE_FLAG_-Wextra-semi-stmt
-- Performing Test HAVE_FLAG_-Wextra-semi-stmt - Success
-- Performing Test HAVE_FLAG_-Wnoweak-vtables
-- Performing Test HAVE_FLAG_-Wnoweak-vtables - Failed
-- Performing Test HAVE_FLAG_-ggdb3
-- Performing Test HAVE_FLAG_-ggdb3 - Success
-- Compiling for dynamic library use
-- GIT hash found: c02904b1a85ae3ab54f207607097758582abaf22
-- PROJECT_VERSION: 5.11.14
-- PROJECT_VERSION_MAJOR: 5
-- PROJECT_VERSION_MINOR: 11
-- PROJECT_VERSION_PATCH: 14
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options) (Required is at least version "1.46.0")
-- Not compiling detailed statistics. The system is faster without them
-- Manpage will be created and installed
-- Found ZLIB: /usr/lib/libz.so (found version "1.3")  
-- OK, Found ZLIB!
-- Performing Test HAVE__FPU_SETCW
-- Performing Test HAVE__FPU_SETCW - Success
-- Found FPU code for yalsat: fpu_control.h, _FPU_SINGLE, _FPU_DOUBLE
-- Only building executable with few command-line options because the boost program_options library were not available
-- All defines at startup:  -DRDB0_ONLY_FEATURES -DBOOST_TEST_DYN_LINK -DUSE_ZLIB -DYALSAT_FPU
-- Performing Test HAVE_FLAG_-Wno-bitfield-constant-conversion
-- Performing Test HAVE_FLAG_-Wno-bitfield-constant-conversion - Success
-- Performing Test HAVE_FLAG_-Wlogical-op
-- Performing Test HAVE_FLAG_-Wlogical-op - Failed
-- Performing Test HAVE_FLAG_-Wrestrict
-- Performing Test HAVE_FLAG_-Wrestrict - Failed
-- Performing Test HAVE_FLAG_-Wnull-dereference
-- Performing Test HAVE_FLAG_-Wnull-dereference - Success
-- Performing Test HAVE_FLAG_-Wdouble-promotion
-- Performing Test HAVE_FLAG_-Wdouble-promotion - Success
-- Performing Test HAVE_FLAG_-Wshadow
-- Performing Test HAVE_FLAG_-Wshadow - Success
-- Performing Test HAVE_FLAG_-Wformat=2
-- Performing Test HAVE_FLAG_-Wformat=2 - Success
-- Performing Test HAVE_FLAG_-Wextra-semi
-- Performing Test HAVE_FLAG_-Wextra-semi - Success
-- Performing Test HAVE_FLAG_-pedantic
-- Performing Test HAVE_FLAG_-pedantic - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Deprecation Warning at utils/drat-trim/CMakeLists.txt:21 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- LIB directory is 'lib'
-- BIN directory is 'bin'
-- Doing a RelWithDebInfo build
-- build type is RelWithDebInfo
-- OK, Found ZLIB!
CMake Warning at CMakeLists.txt:796 (message):
  Testing is disabled


-- Configuring done (6.0s)
CMake Error at CMakeLists.txt:544 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<TARGET_FILE:cryptominisat5-bin>

  No target "cryptominisat5-bin"


CMake Error at CMakeLists.txt:544 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<TARGET_FILE:cryptominisat5-bin>

  No target "cryptominisat5-bin"


CMake Error at CMakeLists.txt:544 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<TARGET_FILE:cryptominisat5-bin>

  No target "cryptominisat5-bin"


CMake Error at CMakeLists.txt:544 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<TARGET_FILE:cryptominisat5-bin>

  No target "cryptominisat5-bin"


-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by mister-walter** [comment] 2023-10-02 23:27
I'm not able to reproduce in a fresh Arch Docker container so maybe this is highly specific to my machine, in which case it might make sense to drop this issue.

**Comment by msoos** [comment] 2023-10-13 22:22
Yeah, something is really weird. I have literally the same exact version of cmake as you, and I can't reproduce it. Perhaps a fresh `git clone` and a fresh `build` directory will fix it. In the meanwhile, it seems like you have managed to fix it? I'm closing because it seems like the issue is fixed for you. It was a weird one, though!

Thanks for reporting, and please do re-open/open a new one if you find something odd! Thanks again,

Mate

**Closed by msoos** 2023-10-13 22:22 UTC

**Comment by msoos** [comment] 2024-01-14 16:27
Hi,

I now have a fully working static compilation pipeline for Windows, Mac, and Linux here: https://github.com/msoos/cryptominisat/actions/runs/7514512194 Check the `artifacts` at the bottom, you will find a binary for you!

Cheers!
