### ISSUE TITLE
time_limit might not always work

### ISSUE THREAD

**Issue by arealuser** [msoos/cryptominisat#610] opened 2020-03-30 22:08 UTC
Hi,
Thank you for writing this amazing application.
I have a python project I am working on, where I am trying to solve a SAT, but whether I solved it or not, I need to return something quickly.
So I tried using the time_limit parameter of pycryptominisat.Solver but it didn't seem to have much of an effect...

```
from pycryptosat import Solver as SATSolver
SAT_TIME_LIMIT = 1
clauses = get_clauses() #returns a few hundred short clauses
t0 = time.time()
solver = SATSolver(threads=4, time_limit=SAT_TIME_LIMIT)
solver.add_clauses(clauses)
sat, sol = solver.solve()
print time.time() - t0
```

I usually get values around 0.05 seconds, but sometimes I must be using a harder SAT, and the runtime spikes to ~30 seconds (despite the time_limit).

Any ideas? Am I using the functions wrong? Do you have any workarounds / "hacky" solutions?

PS I am running the code on an ubuntu machine via ipython notebook (python 2.7).

Also, I don't think this is the same issue as https://github.com/msoos/cryptominisat/issues/584, since I see that all 4 CPUs of my machine are almost fully devoted to the solver (so it's not that the solver is only getting 1 second of CPU time).

Thanks in advance!

**Comment by cipherboy** [comment] 2020-03-30 22:35
\o Hey @arealuser. 

Why not move the work to a separate thread/process and let Python handle killing them for you? 

Something like the following (Python 3.2+)?

```python
#!/usr/bin/python3

import pycryptosat
import concurrent.futures

print(pycryptosat)

def worker(clauses):
    solver = pycryptosat.Solver(threads=4)
    solver.add_clauses(clauses)
    sat, sol = solver.solve()
    return sat, sol
    
problem_1 = ((1,), (-2,), (-3,), (-1, 2, 3))

with concurrent.futures.ProcessPoolExecutor() as executor:
    promise = executor.submit(worker, problem_1) 
    try:
        sat, sol = promise.result(timeout=1)
        print(sat, sol)
    except TimeoutError:
        # No dice
        print("Unable to solve in the given time!")
```

(I think we want a separate process because it'll allow python to forcefully kill the `pycryptosat` child -- IIRC the Python module doesn't handle signals gracefully). 

Thoughts?

**Comment by arealuser** [comment] 2020-03-31 07:51
Thank you for the fast reply!

I tried your solution, but unfortunately, it didn't solve the problem:
```python
from concurrent.futures import ProcessPoolExecutor, TimeoutError
from pycryptosat import Solver as SATSolver
import time

def worker(clauses):
    solver = SATSolver(threads=4)
    solver.add_clauses(clauses)
    sat, sol = solver.solve()
    return sat, sol

t0 = time.time()
with ProcessPoolExecutor() as executor:
    promise = executor.submit(worker, clauses) 
    try:
        sat, sol = promise.result(timeout=1)
        print sat
    except TimeoutError:
        # No dice
        print "Unable to solve in the given time!", time.time() - t0

print 'This took %.2f Seconds' % (time.time() - t0)
```
And this printed:
Unable to solve in the given time! 1.22828102112
This took 29.77 Seconds

(so it got a TimeoutError after about 1 second, but then failed to shut down the internal processes)

After trying some of the ideas in https://stackoverflow.com/questions/42782953/python-concurrent-futures-how-to-make-it-cancelable/45515052#45515052 , in the end I managed to get it to work with pebble.
For the benefit of anyone who might have similar problems in the future, this is the code that worked for me:
```python
from pebble import ProcessPool
from concurrent.futures import TimeoutError
from pycryptosat import Solver as SATSolver
import time

def worker(clauses):
    solver = SATSolver(threads=4)
    solver.add_clauses(clauses)
    sat, sol = solver.solve()
    return sat, sol

t0 = time.time()
with ProcessPool() as pool:
    promise = pool.schedule(worker, args=[clauses], timeout=1)
    try:
        sat, sol = promise.result()
        print sat
    except TimeoutError:
        # No dice
        print "Unable to solve in the given time!", time.time() - t0

print 'This took %.2f Seconds' % (time.time() - t0)
```
Unable to solve in the given time! 1.4741590023
This took 1.62 Seconds

I might be nice to see something similar (but less hacky :) ) in future versions of the SAT solver, but this solves my problem for now.

Thank you again for your help and thanks for writing this software :)

**Comment by cipherboy** [comment] 2020-03-31 14:48
@arealuser Oh I didn't write it, all that credit goes to @msoos! 

It is a very simple fix conceptually: add calls to [`PyErr_CheckSignals(...)`](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_CheckSignals) in the hot path of the solver.

This is problematic for a few reasons:

 1. Now `libcryptominisat5.so` (the core solver) depends on Python,
 2. Performance is decreased significantly.

Taking 1, we have the following dependency diagram:

```
       -------------
       | script.py |
       -------------
             |
            dep
             |
             v
      ---------------
      | pycryptosat |
      ---------------
        /          \
       v            v
----------     ---------------------
| cython |     | libcryptominisat5 |
----------     ---------------------
                        ^
                        |
               ---------------------
               | cryptominisat cli |
               ---------------------
```

If we were to add this call, `libcryptominisat5` would need to link against `cython`. This means that users of the `cryptominisat` command line interface would also have a link against `cython`, which isn't desirable in most cases. It'd probably be best to have two separate libraries (one compiled for python and one for the CLI), but that'd make packaging in distributions harder. This could be `#ifdef`'d to only happen when Python is available, but it makes debugging harder (what compile options, ...). 

Taking 2, this would need to go in the hot path somewhere. I think the check would invoke a system call in most cases, which would decrease performance significantly. This isn't something we'd want most people to use. We could do a runtime check (have `pycryptosat` construct CryptoMiniSat's `SATSolver` differently than the CLI does), which'd have smaller performance impact when it is called from the CLI, but SAT solver performance matters a lot and I don't think Mate would want to do this either.

--- 

If you want, you're happy to add this and submit a PR. I've looked into it in the past and thought it was a bit much (for my use case). 

---

Another thought is you can use conflicts to limit the running time somewhat and check if its within the time limit. It wouldn't be perfect. But it would help ensure you get back to Python runtime (at the cost of having to bump the conflict limit and redo the solve if there's still time remaining).

Just some thoughts if you don't like the current idea :-)

**Comment by msoos** [comment] 2020-03-31 21:27
Hi!

First of all, thanks for the bug report. This _should_ work. So I am a bit confused. Inspired by your bug report, I wrote a test into my standard test-suite, and it certainly works for me -- we'll see if Travis CI/AppVeyor also confirms that it works on other OSes. The diff was: 7432bd6a6cfcedcefe51362cc039ded9193849fd. My test is:

```
class TestSolveTimeLimit(unittest.TestCase):

    def get_clauses(self):
        cls = []
        with open("tests/f400-r425-x000.cnf", "r") as f:
            for line in f:
                line = line.strip()
                if len(line) == 0:
                    continue
                if line[0] == "p":
                    continue
                if line[0] == "c":
                    continue
                line = line.split()
                line = [int(l.strip()) for l in line]
                assert line[-1] == 0
                cls.append(line[:-1])

        return cls


    def test_time(self):
        SAT_TIME_LIMIT = 1
        clauses = self.get_clauses() #returns a few hundred short clauses
        t0 = time.time()
        solver = Solver(threads=4, time_limit=SAT_TIME_LIMIT)
        solver.add_clauses(clauses)
        sat, sol = solver.solve()
        took_time = time.time() - t0
        self.assertLess(took_time, 2)
```

Where the file `tests/f400-r425-x000.cnf` cannot be solved even in under 1 hour. The system takes almost exactly 1 second to exit, reporting that it doesn't find a solution (i.e. neither SAT nor UNSAT). I have also tested the binary and that also works with the time limit. I added a diff just to test the library interface: 934cf908e9f290cc31252b9454a82aef5ca9585b and that shows that it works, too. What's good is now I have a test for the timeout! That's great news, I think. But I don't know what's going on. 

Can you please give me the full `cmake` output (delete the `build` directory, and re-configure), your full `make` output (after full delete and full re-configure), your OS type (Linux, MacOS, Windows), your OS version, you python version, etc?

Thanks,
Mate

**Comment by arealuser** [comment] 2020-04-06 08:53
Hi,

Sorry for the delayed response (I was swamped trying to complete my project on time).

@msoos 
I attached the stdouts of the make and the cmake.
The make also printed some compilation warnings which I also attached, but I don't think they are relevant to this problem.

My OS is a Linux version 4.15.0-74 (Ubuntu 7.4.0)

I am running python version:
2.7.13 (default, Jul 22 2017, 10:05:34) 
[GCC 5.4.0 20160609]

Also, I don't know if it matters, but I am running python through a Jupyter 4.3.0 ipython notebook (the one installed by default with SageMath).

[cryptominisat_make_stderr.txt](https://github.com/msoos/cryptominisat/files/4433459/cryptominisat_make_stderr.txt)
[cryptominisat_cmake_output.txt](https://github.com/msoos/cryptominisat/files/4433461/cryptominisat_cmake_output.txt)
[cryptominisat_make_output.txt](https://github.com/msoos/cryptominisat/files/4433462/cryptominisat_make_output.txt)

@cipherboy 
I'm sorry, but I didn't understand much of what you wrote (I don't know _that_ much about computers)...
Is there something you wanted for me to run in order to solve the problem locally, or were you offering a solution to the problem in general?


Thanks again for all of your help :)

**Comment by msoos** [comment] 2020-04-06 21:56
Oh, I know what's going on. You are measuring BOTH the time to add the clauses AND the time to solve. Adding clauses takes time. That may be what the problem is. Please edit the code you had above:

```
from pycryptosat import Solver as SATSolver
SAT_TIME_LIMIT = 1
clauses = get_clauses() #returns a few hundred short clauses
t0 = time.time()
solver = SATSolver(threads=4, time_limit=SAT_TIME_LIMIT)
solver.add_clauses(clauses)
sat, sol = solver.solve()
print time.time() - t0
```

to this:

```
from pycryptosat import Solver as SATSolver
SAT_TIME_LIMIT = 1
clauses = get_clauses() #returns a few hundred short clauses
solver = SATSolver(threads=4, time_limit=SAT_TIME_LIMIT)
solver.add_clauses(clauses)
t0 = time.time()
sat, sol = solver.solve()
print time.time() - t0
```

I believe this will fix the apparent issue that the time printed is wrong.

If that's the case, then you can try to add the clauses 1000 by 1000 and check the time. If it's above your threshold, abort the loop and don't call the `solve()` function. I believe the solver is not taking too much time (perhaps going over the limit by a few seconds). Instead, it's the adding of the clauses that takes so much time. Can you please check?

Thanks,

Mate

**Comment by msoos** [comment] 2021-03-02 20:05
I think this is related: https://github.com/msoos/cryptominisat/issues/486 I will try to get to the bottom of that. It will still not make the parsing immediate, i.e. adding clauses will still take time, but it should be less time :)

**Comment by msoos** [comment] 2021-03-02 20:17
Ah! #486 has been solved -- can you please check if this mostly fixes your issue?

**Comment by msoos** [comment] 2021-03-20 14:47
Closing, I believe #486 fixed it!

**Closed by msoos** 2021-03-20 14:47 UTC
